= Бухгалтерская отчетность 1,6 млн российских компаний: Как получить и как использовать?
Евгений Погребняк <e.pogrebnyak@gmail.com>
v0.0.1, January 29, 2019: Simple prose
:source-highlighter: coderay

Мы сделали интерфейс для удобного доступа к открытым данным 
корпоративной отчетности российских компаний (РСБУ) за 2012-2017 год. 
Пользователи могут получить эти данные в виде преобразованных CSV файлов,
с которыми далее можно работать средствами https://pandas.pydata.org/[pandas] 
или https://www.r-project.org/[R].  


В преобразованных CSV файлах записаны заголовки с названиями столбцов (переменных). Размер исходных файлов, составляющий 0,7-2,3 Гб за один год, уменьшается примерно в два раза за счет удаления пустых и неиспользуемых столбцов. 

Код для доступа к данным и примеры их использования находятся в репозитарии <https://github.com/ru-corporate/sandbox>. Исходные файлы находятся на 
сайте Росстата.

== Как получить отчетность?

Установка пакета:

[source]
----
git clone https://github.com/ru-corporate/sandbox.git // <1>
cd sandbox
pip install -r requirements.txt 
pip install . // <2>
----
<1> вместо git также можно скачать и распаковать zip файл
<2> устанавливаем `boo` локально

Загрузка данных за 2012 год:

[source, python]
----
import boo 
boo.download(2012) // <1>
boo.build(2012) // <2>
df = boo.read_dataframe(2012) // <3>
----
<1> скачиваем исходные данные 
<2> преобразуем их и записываем в новый файл (см. ниже)
<3> читаем данные из преобразованного файла в фрейм `pandas`

Для преобразования отчетности используется следующий алгоритм:

. ввести названия столбцов, отражающие смысл переменных бухгалтерской 
  отчетности (например, счет "Основные средства", код `1150`, 
  обозначение в файле `of`)
. уменьшить размер файла за счет удаления пустых и неиспользуемых столбцов
. привести все строки к одинаковым единицам измерения (тыс. руб.)
. создать новые столбцы: 
   * короткое название компании
   * код ОКВЭД разбить на три уровня
   * определить регион по ИНН
. убрать дублирование данных по коду ИНН (~30-40 организаций)
. указать тип переменных по столбцам, чтобы ускорить чтение данных

Дополнительная информация о загрузке и преобразовании данных 
находится в https://github.com/ru-corporate/sandbox[репозитарии 
ru-corporate/sandbox].

== Как использовать?

Сферы применения отчетности:

- рейтинги крупнейших компаний и отраслевые рейтинги
- финансовая устойчивость и эффективность компаний
- оценка стоимости компаний, кредитный риск, банкротства
- оценка экономической концентрация в отрасли
- анализ налоговых поступлений и налоговой нагрузки 
- инвестиционный процесс (кто инвестирует в расширение мощностей) 
- региональная экономика и планирование (городской транспорт, ЖКХ, TБО)

== Что хотим показать?

* краткий код доступа к данным 
* полноту данных
* разметку по отраслям
* крупнейшие холдинги
* красивые графики 


== Возможные разделы

* Карта экономики
* Использование в обучении финансам

== Учим asciidoc

=== Расширения:

* Можем ли вставить таблицы из pd.DataFrame?
* https://opendevise.github.io/presentation-asciidoctor-new-noteworthy-beyond/#23[
asciidoctor-new-noteworthy-beyond]

=== Базовые знания:

* https://raw.githubusercontent.com/asciidoctor/asciidoctor.org/master/docs/asciidoc-syntax-quick-reference.adoc[asciidoc-syntax-quick-reference.adoc]
* https://gist.githubusercontent.com/epogrebnyak/593873598a511f9a799bc2743db28b9e/raw/8561febaeef274173e8fbffd98f641be7dece87b/asciidoc_example.adoc[asciidoc_example.adoc]
